### ISSUE TITLE
Notification to Slack is not happening using thold-slack.py in SMTP

### ISSUE THREAD

**Issue by ibnunowshad** [jamesboswell/thold-slack#5]
Notification to Slack is not happening when `thold-slack.py `running behind SMTP Relay server.

Setup:
1. Cacti Server - `Server 01`
2. SMTP Server - `Server 02`
3. DNS Server - `Server 03`

All  three components are running in three different servers. Cacti THOLD is working fine as expected and getting notification mail. When parsing the mail through different SMTP Server notifications to slack is not coming up. But working fine when running sendmail from same Cacti Server not working when running from other servers same sendmail.

**Comment by jamesboswell** [comment]
@ibnunowshad `Server01` is configured to send mail to `Server02`, yes?  Is the `thold-slack.py` script setup on `Server02`?

`thold-slack.py` is a Python script designed to run under Sendmail restricted shell.    A few things to check

1. Cact serveri is sending THOLD emails to `Server02`,  via sendmail or SMTP settings 
2. `Server02` is configured to use *smrsh* and has a valid Python install
3. `thold-slack.py` is in the smrsh dir and marked as executable (chmod +x)
4.   `/etc/aliases` is something you might want to check on `Server02` it should contain something like this
       ```thold-slack:    | /etc/smrsh/thold-slack.py```

**Comment by ibnunowshad** [comment]
@jamesboswell 

1. `Server01` is configured to use `Server02` as SMTP Server to send mail to other email IDs configured in Cacti(Server01).
2. `thold-slack.py` script is running in `Server01` where Cacti is running.
3. `thold-slack.py` is not under smrsh dir, but marked as executable and running fine in `Server01` if I fire command `sendmail cacti@server01.domain.com < /tmp/2.txt` where `/tmp/2.txt` contain mail contents for testing `To: cacti@server01.domain.com`
4. `/etc/aliases` in `Server01` contains `cacti: | /usr/share/cacti/thold-slack.py` where python script running.

So, questions;

1. Do you suggest smrsh only for secure way to run the script?
2. I do have `domain.com` as my external mail server where the mail service hosted. My assumption is `Server02` is trying to `server01.domain.com` which is the hostname of `Server01` is sending request to external mail server instead of sending to `Server01` when using mail id as `cacti@server01.domain.com` in THOLD configurations in Cacti. So do you suggest to run script `thold-slack.py` in SMTP Server `Server02` instead of Cacti Server `Server01`. Yes? then my assumption will be true again. Correct me if I am wrong.

**Comment by jamesboswell** [comment]
@ibnunowshad 
>Do you suggest smrsh only for secure way to run the script?
Yes.  It's more secure, see 1st [paragraph here](http://www.faqs.org/docs/securing/chap22sec182.html)   It's purely up to you

In regards to your setup.   I have something similar.   Here is my setup

1. In Cacti GUI,  setup THOLD or THOLD template to send email to  `thold-slack`
2. In `/etc/aliases`  add the following line `thold-slack:    | /etc/smrsh/thold-slack.py`
3. Run `sudo newaliases`
4.  Sendmail is configured to use Smarthost ```define(`SMART_HOST', 'smtp-server.domain.com')dnl```

So any THOLD or other Cacti alerts configured to email to `thold-slack`  (no @domain)  use the local alias which is piped to `thold-slack.py`    Any other email addresses go to my SMTP server using Sendmail smart host,  to relay to my internal relay  (Server02 for you)

**Comment by ibnunowshad** [comment]
Thanks James. Let me try it out. Already till point 3 taken care and used. 4th point you suggest to include in script define section?

-Ibrahim
Sent from my iPhone

On 21-Sep-2017, at 02:02, James Boswell <notifications@github.com<mailto:notifications@github.com>> wrote:


@ibnunowshad<https://github.com/ibnunowshad>

Do you suggest smrsh only for secure way to run the script?
Yes. It's more secure, see 1st paragraph here<http://www.faqs.org/docs/securing/chap22sec182.html> It's purely up to you

In regards to your setup. I have something similar. Here is my setup

  1.  In Cacti GUI, setup THOLD or THOLD template to send email to thold-slack
  2.  In /etc/aliases add the following line thold-slack: | /etc/smrsh/thold-slack.py
  3.  Run sudo newaliases
  4.  Sendmail is configured to use Smarthost define(`SMART_HOST', 'smtp-server.domain.com<http://smtp-server.domain.com>')dnl

So any THOLD or other Cacti alerts configured to email to thold-slack (no @Domain<https://github.com/domain>) use the local alias which is piped to thold-slack.py Any other email addresses go to my SMTP server using Sendmail

**Comment by jamesboswell** [comment]
@ibnunowshad  4th point is Sendmail configuration,   `/etc/mail/sendail.mc` on RHEL.   It will depend on your environment and system

**Comment by ibnunowshad** [comment]
Exactly I didn’t local alias suffixed with mail id for THOLD. But no luck.

-Ibrahim
Sent from my iPhone

On 28-Sep-2017, at 02:22, James Boswell <notifications@github.com<mailto:notifications@github.com>> wrote:


@ibnunowshad<https://github.com/ibnunowshad> 4th point is Sendmail configuration, /etc/mail/sendail.mc on RHEL. It will depend on your environment and system

**Comment by jamesboswell** [comment]
@ibnunowshad without more information I'm not sure I can help you here.   Sounds like a configuration issue with your Sendmail setup, and not specific to thold-slack.    

You should have your Cacti server (Server01) setup with an alias to the thold-slack script,  and relay all other mail to your Server02.   This is doable, I suggest double checking your Sendmail setup.    

Not seeing a specific bug or issue with the script I'm going to close this issue.   All the best.

**Comment by 240sx1127** [comment]
Hi James,
When I trying to add email sending to thold-slack in Cacti GUI, I got this error. Error: You must provide at least one recipient email address. It's seem like the format only allowed email address format.
