### ISSUE TITLE
error on line 146

### ISSUE THREAD

**Issue by semakka1975** [jamesboswell/thold-slack#6]
hi,
I'm getting an error:
> root@cacti:/etc/mail/smrsh# cat email.eml | ./thold-slack.py
  File "./thold-slack.py", line 146
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

cacti 1.x, thold 1.x, python3

**Comment by semakka1975** [comment]
It was the python version. installed v2 and works.

**Comment by jamesboswell** [comment]
Glad to hear you worked this out.   `thold-slack` as it's currently written is not correct for Python 3.  I recommend Python 2.7.x where possible.    

Proper Python 3 support is something I'd like to eventually do but have no current plans for at this time.  Happy to entertain pull requests.
